### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by CARocha** [IMGIITRoorkee/django-filemanager#13]
Hi, the question is dead or works for compatible version django 1.10.x???

thank

**Comment by kartikp1995** [comment]
We have not tried this with Django >1.7. But we are planning to upgrade this in short term.

**Comment by akki** [comment]
I think this is now being tracked in https://github.com/IMGIITRoorkee/django-filemanager/issues/22. If that's the case we can close this one.

**Comment by akki** [comment]
To track the work related to upgrading the Django version please refer #22 .
