### ISSUE TITLE
Add a CI to the repo

### ISSUE THREAD

**Issue by rohithasrk** [IMGIITRoorkee/django-filemanager#17]
We could use Travis CI, Circle CI or any other CI depending on what is beneficial. Continuous integration is basically used to build the repo and check for errors. Which will play a major role after the tests have been written and make things easier. Just need to add some files which will instruct the CI to do so. #15 needs to be completed as soon as possible.

**Comment by dhruvkb** [comment]
Instead of adding fancy stuff like CI, which are not the need of the hour, we should probably concentrate our efforts on more pressing issues like ensuring compatibility with Python >= 3.5, Django >= 1.10 and closing issues like #9 and #12.

**Comment by rohithasrk** [comment]
Travis is not a something fancy @dhruvkb. It helps us debug things to a great extent which I've come across. Yes. My primary aim is concentrate on more pressing issues like ensuring compatibility. By using a CI software like Travis I'd just have to add a single line in the yml file which throws so many errors and therefore ease the debugging process. This is how things are generally done in big open source organisations and I feel these are some things we'll have to learn. :-)

**Comment by kartikp1995** [comment]
#18 Added Travis CI. Let's see what can we do with that. :)
