### ISSUE TITLE
Make Python 3/ Django 1.11 functional

### ISSUE THREAD

**Issue by rohithasrk** [IMGIITRoorkee/django-filemanager#22]

**Comment by GudarJs** [comment]
May I help you with this issue? I have experience migrating django apps and python 2 to 3.

**Comment by meetvora** [comment]
Sure! This is would be great.

**Comment by GudarJs** [comment]
Great! I will work on this later. Can you assign this to me? it's for tracking this thread.

**Comment by rohithasrk** [comment]
@GudarJs Are you working on it?

**Comment by rohithasrk** [comment]
@GudarJs still on it?

**Comment by guy881** [comment]
Hey, @rohithasrk I would love to help with this one!

**Comment by rohithasrk** [comment]
Sure. Go on!

**Comment by guy881** [comment]
I've made a pull request, check it out, please.
https://github.com/IMGIITRoorkee/django-filemanager/pull/65

**Comment by akki** [comment]
Thanks @guy881 - this is resolved in master as c161f30.
