### ISSUE TITLE
Display actions when right clicked on DOM area

### ISSUE THREAD

**Issue by rohithasrk** [IMGIITRoorkee/django-filemanager#29]
As of now, for cut/ copy we'll need to click on a directory to see the actions possible which is not really intuitive. The goal is to enable actions everywhere on right click.

**Comment by shaddygarg** [comment]
I  would like to work on this issue. I am thinking of adding a right click menu on the DOM element which includes downloading the current directory, paste option if the clipboard is not empty and make a folder option in it. Any more suggestions are welcome.

**Comment by rohithasrk** [comment]
Closed by merging #49
